-- MySQL Script generated by MySQL Workbench
-- Wed Jul 19 11:47:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `site` ;

CREATE TABLE IF NOT EXISTS `site` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `year` YEAR NULL,
  `address` VARCHAR(150) NOT NULL,
  `maplink` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `activity` ;

CREATE TABLE IF NOT EXISTS `activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `activity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin` ;

CREATE TABLE IF NOT EXISTS `admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `hashedPassword` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site_has_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `site_has_activity` ;

CREATE TABLE IF NOT EXISTS `mydb`.`site_has_activity` (
  `site_id` INT NOT NULL,
  `activity_id` INT NOT NULL,
  PRIMARY KEY (`site_id`, `activity_id`),
  INDEX `fk_site_has_activity_activity1_idx` (`activity_id` ASC) VISIBLE,
  INDEX `fk_site_has_activity_site_idx` (`site_id` ASC) VISIBLE,
  CONSTRAINT `fk_site_has_activity_site`
    FOREIGN KEY (`site_id`)
    REFERENCES `mydb`.`site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_site_has_activity_activity1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `mydb`.`activity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `site`
-- -----------------------------------------------------
INSERT INTO 
  site (
    name,
    year,
    address,
    maplink
  ) 
VALUES 
  (
    "Saint-Eloi Historique",
    1921,
    "57 ch. du Sang de Serp, 31200 Toulouse",
    "https://www.google.fr/maps/place/57+Chem.+du+Sang+de+Serp,+31200+Toulouse/@43.6145813,1.4260571,17z/data=!3m1!4b1!4m6!3m5!1s0x12aebb4751d0114d:0x8205a48119dd8a3d!8m2!3d43.6145774!4d1.428632!16s%2Fg%2F11c2h8tzp8?entry=ttu"
);

INSERT INTO 
  site (
    name,
    year,
    address,
    maplink
  ) 
VALUES 
  (
    "Saint-Martin",
    1965,
    "316 route de Bayonne, 31000 Toulouse",
    "https://www.google.fr/maps/place/316+Rte+de+Bayonne,+31300+Toulouse/@43.6118883,1.3700106,17z/data=!3m1!4b1!4m6!3m5!1s0x12aebaa245f2e193:0x781eb116cd550ce!8m2!3d43.6118844!4d1.3725855!16s%2Fg%2F11bw40ch63?entry=ttu"
);

INSERT INTO 
  site (
    name,
    year,
    address,
    maplink
  ) 
VALUES 
  (
    "Clément Ader",
    1989,
    "13 avenue Yves Brunaud, 31770 Colomiers",
    "https://www.google.fr/maps/place/13+Av.+Yves+Brunaud,+31770+Colomiers/@43.6151736,1.3506032,17z/data=!3m1!4b1!4m6!3m5!1s0x12aeb0143ccc25e3:0x683762c3c9f13684!8m2!3d43.6151697!4d1.3531781!16s%2Fg%2F11csjv0kd4?entry=ttu"
);

INSERT INTO 
  site (
    name,
    year,
    address,
    maplink
  ) 
VALUES 
  (
    "Louis Breguet",
    1976,
    "15 avenue Yves Brunaud, 31770 Colomiers",
    "https://www.google.fr/maps/place/15+Av.+Yves+Brunaud,+31770+Colomiers/@43.6161866,1.3506976,17z/data=!3m1!4b1!4m6!3m5!1s0x12aeb0116b7fdde5:0x4dc52b63af2d170b!8m2!3d43.6161827!4d1.3532725!16s%2Fg%2F11cp5_xcpm?entry=ttu"
);

INSERT INTO 
  site (
    name,
    year,
    address,
    maplink
  ) 
VALUES 
  (
    "Jean Mermoz",
    2015,
    "86 route de Toulouse, 31700 Cornebarrieu",
    "https://www.google.fr/maps/place/Airbus+J+Mermoz/@43.6462594,1.3504728,17z/data=!3m1!5s0x12aeafec9b58e17d:0xc8560bbc2c6b6a75!4m15!1m8!3m7!1s0x12aeafea58ba793f:0x24c5664de247403e!2s86+Rte+de+Toulouse,+31700+Cornebarrieu!3b1!8m2!3d43.646341!4d1.348488!16s%2Fg%2F11c0_w_17k!3m5!1s0x12aeafaac52dd95b:0xd36e4d402f2f91f4!8m2!3d43.6465146!4d1.3521259!16s%2Fg%2F11g2_h4fgr?entry=ttu"
);

INSERT INTO 
  site (
    name,
    year,
    address,
    maplink
  ) 
VALUES 
  (
    "Jean-Luc Lagardère",
    2004,
    "1 Avenue d'Aéroconstellation, 31700 Cornebarrieu",
    "https://www.google.fr/maps/place/1+Av.+d'A%C3%A9roconstellation,+31700+Blagnac/@43.6551577,1.3564435,17z/data=!3m1!4b1!4m6!3m5!1s0x12aeaf8ef7b4fb69:0xc5c387c3cb512dd9!8m2!3d43.6551538!4d1.3590184!16s%2Fg%2F11c16hf3cq?entry=ttu"
);

INSERT INTO 
  site (
    name,
    year,
    address,
    maplink
  ) 
VALUES 
  (
    "ZAC Aéroconstellation",
    2006,
    "Rue Félix Kracht, 31700 Cornebarrieu",
    "https://www.google.fr/maps/place/A%C3%A9roconstellation+(Airbus)+Poste+Logistique/@43.6600189,1.3463582,17z/data=!3m1!4b1!4m6!3m5!1s0x12aeaf1287c18807:0xc0b293e811c82f47!8m2!3d43.660015!4d1.3489331!16s%2Fg%2F11hfmf4qp6?entry=ttu"
);

-- -----------------------------------------------------
-- Table `activity`
-- -----------------------------------------------------
INSERT INTO
  activity (
    activity
  )
VALUES
  (
    "Montage"
);

INSERT INTO
  activity (
    activity
  )
VALUES
  (
    "Electricité"
);

INSERT INTO
  activity (
    activity
  )
VALUES
  (
    "Usinage"
);

INSERT INTO
  activity (
    activity
  )
VALUES
  (
    "Tôlerie"
);

INSERT INTO
  activity (
    activity
  )
VALUES
  (
    "Lycée"
);

INSERT INTO
  activity (
    activity
  )
VALUES
  (
    "R & D"
);

-- -----------------------------------------------------
-- Table `site_has_activity`
-- -----------------------------------------------------

INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    1,
    1
  );

INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    1,
    3
  );

INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    1,
    4
  );

INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    1,
    5
  );

INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    2,
    1
  );

INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    2,
    6
  );

INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    3,
    1
  );

INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    3,
    2
  );

INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    4,
    1
  );

INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    5,
    1
  );

  INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    5,
    2
  );

  INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    6,
    1
  );

INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    6,
    2
  );

INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    7,
    1
  );

INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    7,
    2
  );

INSERT INTO
  site_has_activity (
    site_id,
    activity_id
  )
VALUES
  (
    7,
    6
  );

-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
INSERT INTO
  admin (
    name,
    hashedPassword
  )
VALUES
  (
    "admin",
    "$argon2id$v=19$m=65536,t=5,p=1$MGd5EHqEaOdB244wPrOTow$iiVOg15m03O8ZG1wNGNDt3X18EoenCep5FgnfIIQwJU"
  );

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
